version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-26-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Install Maven
          command: sudo apt-get update; sudo apt-get install maven
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./scripts/install-dependencies.rb
      - save_cache:
          paths:
            - ~/.gradle
            - ~/.m2
          key: jars-{{ checksum "build.gradle" }}
      - run:
          name: Run Tests
          command: |
            ./gradlew clean assemble compileTest --info --stacktrace
            NO_REBUILD=true ./gradlew test --no-rebuild --continue --info --stacktrace
      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: build/reports
          destination: reports
