version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-26-alpha
    resource_class: large
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Calculate Cache Hash
          command: find . \( -name \*.gradle -or -name \*.groovy -or -name \*.sh -or -name \*.rb -or -name circle.yml \) -exec shasum {} \; > .cache-hash
      - run:
          name: Install Maven
          command: sudo apt-get update; sudo apt-get install maven
      - restore_cache:
          key: cache-{{ checksum ".cache-hash" }}
      - run:
          name: Download Dependencies
          command: |
            ./scripts/install-dependencies.rb
            ./gradlew dependencies prefetchSdks
      - save_cache:
          paths:
            - ~/.gradle
            - ~/.m2
          key: cache-{{ checksum ".cache-hash" }}
      - run:
          name: Build
          command: ./gradlew clean assemble compileTest --info --stacktrace
      - run:
          name: Run Tests 1/2
          command: NO_REBUILD=true ./gradlew test --no-rebuild --continue --info --stacktrace --no-daemon --max-workers 1 -Drobolectric.enabledSdks=16 #,17,18,19,21
      - run:
          name: Run Tests 2/2
          command: NO_REBUILD=true ./gradlew test --no-rebuild --continue --info --stacktrace --no-daemon --max-workers 1 -Drobolectric.enabledSdks=22 #,23,24,25,26
      - run:
          name: Collect Test Results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: build/reports
          destination: reports
